language: objective-c
osx_image: xcode7.2
script:
  - xctool -project TestsAndSample/TestsAndSample.xcodeproj -scheme Tests64 test
  - xctool -project TestsAndSample/TestsAndSample.xcodeproj -scheme Tests32 test
